import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Globe } from "@/components/ui/globe";
import { AnimatedThemeToggler } from "@/components/ui/animated-theme-toggler";
import { SmoothCursor } from "@/components/ui/smooth-cursor";
import { Input } from "@/components/ui/input";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased cursor-none`}
      >
      <div className="flex justify-end"><AnimatedThemeToggler className="cursor-none  "/><SmoothCursor /></div>
        {children}
      </body>
    </html>
  );
}
